### ISSUE TITLE
Chromosomes are not integers

### ISSUE THREAD

**Issue by winni2k** [imgag/IGV_genome_ensembl#1]
Hi, 
Thanks for this piece of code. I thought I might be able to use it, but I have hit the maximum number of bugs I can tolerate on this code, so I am moving on.  In the spirit of leaving things in a better state than I found them, here are the issues I observed while trying to work with the code:

The documentation states that python 2.7 is required, but this code is actually incompatible with python 2.7 (lots of print calls using parentheses). I think the documentation is probably out of date?

It appears to me as if chromosomes are being coerced to integers here: https://github.com/imgag/IGV_genome_ensembl/blob/1c33b20c8d219769ba0130bf3f28b3d0caaa71e3/gff_to_genepred_converter.py#L144

Naturally, this fails on my GFF file that contains non-integer-named chromosomes.

HTH

**Comment by leonschuetz** [comment]
Thank you for your comment. 

You are right with the documentation. I updated the Python version, but not the readme.

About the integer conversion: The code was originally designed for GRCh37 and the provided gff file and the conversion is required to get the correct order of the chromosomes. ( All non-interger chromosomes have to be entered in the sorting_order dictionary).

For which reference genome/ GFF file do you want to use the code?

Best,
Leon Schütz

**Comment by winni2k** [comment]
Thanks for the reply! 

I was trying to get it to work with GRCh38 + Ensembl v96 GTF/GFF.

I have resorted to mapping the Ensembl v96 CDNAs to GRCh38 using minimap2 and using the resulting BAM as a track for isoform annotation. That sort of works. I also later discovered that the GRCh38 genome that I can download through igv also comes with a gene annotation track, which is good enough for me.

Cheers,
Winni
